import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/_Components/Navbar";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Ad from "@/_Components/Ad";
import Footer from "@/_Components/Footer";
import 'swiper/css';
import CartProvider from "@/Context/CartContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <CartProvider>
          <Ad />
          <Navbar />

          {children}

          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
